config/routes.rb
Rails.application.routes.draw do
  get 'cart/show', to: 'cart#show'
  post 'cart/add'
  delete 'cart/remove', to: 'cart#remove'
  resources :products
  root 'products#index'
  resources :orderables, only: [:index] do
    collection do
      post 'create_order'
      delete 'delete_order/:order_code', to: 'orderables#delete_order', as: 'delete_order'
    end
  end
end

app/models/cart.rb
class Cart
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end

  def products
    orderables.map(&:product)
  end
end

app/models/orderable.rb
class Orderable
  include Mongoid::Document
  include Mongoid::Timestamps

  field :quantity, type: Integer
  field :total_price, type: Integer
  field :order_created, type: Boolean, default: false
  field :code_order, type: String, default: '0000'
  field :session_id, type: String

  belongs_to :product
  belongs_to :cart

  index({ cart_id: 1, product_id: 1 }, { unique: true })

  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :price, type: BigDecimal

  has_many :orderables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_render_cart
  before_action :initialize_cart

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart = session[:cart_id].present? ? find_cart : create_cart
  end

  private

  def find_cart
    Cart.find_by(id: BSON::ObjectId.from_string(session[:cart_id]))
  rescue BSON::ObjectId::Invalid
    nil
  end

  def create_cart
    cart = Cart.create
    session[:cart_id] = cart.id.to_s
    cart
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_cart

  def show
    @cart_items = @cart.orderables.where(order_created: false)
  end

  def add
    @product = Product.find_by(id: params[:id])
    return unless @product

    quantity = params[:quantity].to_i
    CartAdderService.new(cart: @cart, product: @product, quantity: quantity).add_to_cart

    redirect_to products_path
  end

  private

  def initialize_cart
    @cart ||= Cart.find_or_create_by(id: session[:cart_id]) do |cart|
      session[:cart_id] = cart.id
    end
  end
end

app/controllers/orderables_controller.rb
class OrderablesController < ApplicationController
  def index
    @orderables = Orderable.where(order_created: true, session_id: session.id.to_s)
    @orderables_grouped_by_order = @orderables.group_by(&:code_order)
    @order_totals = @orderables_grouped_by_order.transform_values do |orderables|
      orderables.sum(&:total)
    end
    @total_all_orders = @order_totals.values.sum
  end

  def create_order
    @cart = Cart.find(session[:cart_id])
    order_code = generate_order_code
    @cart.orderables.where(order_created: false).each do |orderable|
      orderable.update(order_created: true, code_order: order_code, session_id: session.id.to_s)
    end
    redirect_to orderables_path, notice: 'The order has been saved successfully.'
  end

  def delete_order
    orderables = Orderable.where(code_order: params[:order_code], session_id: session.id.to_s)
    if orderables.destroy_all
      redirect_to orderables_path, notice: 'The order has been deleted successfully.'
    else
      redirect_to orderables_path, alert: 'Error deleting the order.'
    end
  end

  private

  def generate_order_code
    letters = ('A'..'Z').to_a.sample(3).join
    numbers = rand(100..999).to_s
    "#{letters}#{numbers}"
  end

  def calculate_order_totals(orderables_grouped)
    order_totals = {}
    orderables_grouped.each do |order_code, orderables|
      total_price = orderables.sum(&:total)
      order_totals[order_code] = total_price
    end
    order_totals
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_controller_action(controller, action)
    params[:controller] == controller && params[:action] == action
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/orderables_helper.rb
module OrderablesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <h1>Cart</h1>
  <% orderables_to_display = @cart.orderables.where(order_created: false) %>
  <% if orderables_to_display.any? %>
    <%= render partial: "cart/orderables", locals: { orderables: orderables_to_display } %>
    <p>Total: <%= orderables_to_display.sum(&:total) %></p>
    <%= button_to "Save order", create_order_orderables_path, method: :post %>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
<% end %>

app/views/cart/_orderables.html.erb
<% orderables.each do |orderable| %>
  <% product = orderable.product %>
  <div id="<%= "cart-#{product.id}" %>">
    <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
      <strong>Name:</strong>
      <%= product.name %>
      <strong>Price:</strong>
      <%= "$ #{product.price}" %>
      <%= form_with(url: cart_remove_path, method: :delete) do |f| %>
        <%= f.hidden_field :id, value: orderable.id.to_s %>
        <%= f.submit "X" %>
      <% end %>
      <strong>Total:</strong>
      <%= orderable.total %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% unless current_controller_action('orderables', 'index') %>
     <%= render partial: "cart/cart" if @render_cart %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orderables/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <h1>Cart</h1>
  <% if @cart_items.any? %>
    <%= render "cart/orderables", orderables: @cart_items %>
    <p>Total: <%= @cart_items.sum(&:total) %></p>
    <%= button_to "Save order", create_order_orderables_path, method: :post %>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
<% end %>

app/views/orderables/_orderables.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
  <div id="<%= "cart-#{product.id}" %>">
    <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
      <strong>Name:</strong>
      <%= product.name %>  
      <strong>Price:</strong>
      <%= product.price %>
      <%= form_with(url: cart_remove_path, method: :delete) do |f| %> <!-- Cambiado a DELETE -->
        <%= f.hidden_field :id, value: orderable.id.to_s %> <!-- Pasando el ID correcto -->
        <%= f.submit "X" %>
      <% end %>
      <strong>Total:</strong>
      <%= orderable.total %>
    </div>
  </div>
<% end %>

app/views/orderables/index.html.erb
<h1>Created Orders</h1>

<% if @orderables_grouped_by_order.empty? %>
  <p>No orders created.</p>
<% else %>
  <% @orderables_grouped_by_order.each do |order_code, orderables| %>
    <h2>Order: <%= order_code %></h2>
    <p>Order Total: <%= @order_totals[order_code] %></p>
    <ul>
      <% orderables.each do |orderable| %>
        <li>
          Product: <%= orderable.product.name %> - Quantity: <%= orderable.quantity %>
          <br>
          Unit Price: <%= orderable.product.price %> - Total Price: <%= orderable.total %>
          <br>
          Cart ID: <%= orderable.cart.id %>
        </li>
      <% end %>
    </ul>
    <%= button_to 'Delete Order', delete_order_orderables_path(order_code: order_code), method: :delete, data: { confirm: 'Are you sure you want to delete this order?' } %>
  <% end %>
  <h3>Total of All Orders: <%= @total_all_orders %></h3>
<% end %>

<div>
  <%= link_to 'Back to products', products_path %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
    <strong>Name:</strong>
    <%= product.name %>  
    <strong>Price:</strong>
    <%= product.price %>
    <%= form_with(url: cart_add_path) do |f| %>
      <%= f.hidden_field :id, value: product.id %>
      <%= f.number_field :quantity, value: 0, min: 1 %>
      <%= f.submit "Add To Cart" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %><br>
<%= link_to "view orders", orderables_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>